version: '3'
services:
  app:
    build: .
    depends_on:
    - postgres
    ports:
    - 8080:8080
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
